# Reference: https://github.com/i3/i3/blob/next/etc/config
start-at-login = true

# i3 doesn't have "normalizations" feature, that’s why we disable them here.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
    # application binds
    alt-t = 'exec-and-forget open -n /Applications/kitty.app'
    alt-g = 'exec-and-forget open -n /Applications/Google\ Chrome.app'

    # Focus movement (wrap around workspace edges)
    alt-j =         'focus --boundaries-action wrap-around-the-workspace left'
    alt-k =         'focus --boundaries-action wrap-around-the-workspace down'
    alt-l =         'focus --boundaries-action wrap-around-the-workspace up'
    alt-semicolon = 'focus --boundaries-action wrap-around-the-workspace right'

    # Move windows
    alt-shift-j = 'move left'
    alt-shift-k = 'move down'
    alt-shift-l = 'move up'
    alt-shift-semicolon = 'move right'

    # Splits and layouts
    alt-h = 'split horizontal'
    # alt-v = 'split vertical'
    alt-f = 'fullscreen'

    alt-s = 'layout v_accordion'                # stacking
    # alt-w = 'layout h_accordion'                # tabbed
    # alt-e = 'layout tiles horizontal vertical'  # toggle split
    alt-shift-space = 'layout floating tiling'  # toggle floating

    # Workspaces (Alt + [1–0])
    alt-1 = 'workspace 5'
    alt-2 = 'workspace 6'
    alt-3 = 'workspace 7'
    alt-4 = 'workspace 8'
    alt-5 = 'workspace 9'
    alt-6 = 'workspace 10'
    alt-7 = 'workspace 11'
    alt-8 = 'workspace 12'
    alt-9 = 'workspace 13'
    alt-0 = 'workspace 14'

    # ------------------------------
    # Additional workspace shortcuts (Alt + QWER)
    # ------------------------------
    alt-q = 'workspace 1'
    alt-w = 'workspace 2'
    alt-e = 'workspace 3'
    alt-r = 'workspace 4'

    # Move window to workspace (Alt + Shift + [1–0])
    alt-shift-1 = [ 'move-node-to-workspace 5',  'workspace 5']
    alt-shift-2 = [ 'move-node-to-workspace 6',  'workspace 6']
    alt-shift-3 = [ 'move-node-to-workspace 7',  'workspace 7']
    alt-shift-4 = [ 'move-node-to-workspace 8',  'workspace 8']
    alt-shift-5 = [ 'move-node-to-workspace 9',  'workspace 9']
    alt-shift-6 = [ 'move-node-to-workspace 10',  'workspace 10']
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 10'

    # ------------------------------
    # Move window to workspace via QWER
    # ------------------------------
    alt-shift-q = [ 'move-node-to-workspace 1',  'workspace 1']
    alt-shift-w = [ 'move-node-to-workspace 2',  'workspace 2']
    alt-shift-e = [ 'move-node-to-workspace 3',  'workspace 3']
    alt-shift-r = [ 'move-node-to-workspace 4',  'workspace 4']

    # Reload config and enter resize mode
    alt-shift-c = 'reload-config'
    alt-v = 'mode resize'

[workspace-to-monitor-force-assignment]
    1 = ['secondary', 'main']
    2 = ['secondary', 'main']
    3 = ['secondary', 'main']
    4 = 'main'
    5 = ['secondary', 'main']
    6 = ['secondary', 'main']
    7 = ['secondary', 'main']
    8 = ['secondary', 'main']
    9 = ['secondary', 'main']
    10 = ['secondary', 'main']

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

[gaps]
outer.left = [ { monitor."main" = 25 }, 75 ]
outer.right = [ { monitor."main" = 25 }, 75 ]
outer.top = [ { monitor."main" = 15 }, 50 ]
outer.bottom = [ { monitor."main" = 15 }, 50 ]

