-- require("kulala").setup({
-- 	"mistweaverco/kulala.nvim",
-- })
--
-- vim.api.nvim_set_keymap(
-- 	"n",
-- 	"<leader>tk",
-- 	"<cmd>lua require('kulala').toggle_view()<cr>",
-- 	{ noremap = true, silent = true }
-- )
--
-- vim.api.nvim_set_keymap("n", "<leader>fc", "<cmd>require('kulala').from_curl()<cr>", { noremap = true, silent = true })
-- vim.api.nvim_set_keymap("n", "<leader>tc", "<cmd>require('kulala').copy()<cr>", { noremap = true, silent = true })
