#!/bin/sh
# https://github.com/jarun/nnn/wiki/Advanced-use-cases nnn browser integration
# Also nee to wrap the browser binary
# #!/bin/sh
# XDG_CURRENT_DESKTOP=KDE <browser binary> "$@"
while :; do case $1 in
    --getsavefilename) file="$2" break ;;
    --version) printf ""; exit ;;
    --*) shift ;;
    *) break ;;
esac done

file="${file##/*/}"

kitty --class picker sh -c "nnn -J -p - '$file' | awk '{ print system(\"[ -d '\''\"\$0\"'\'' ]\") ? \$0 : \$0\"/$file\" }' > /proc/$$/fd/1"
